### ISSUE TITLE
log_metric() raises warning, doesn't reflect in trial component

### ISSUE THREAD

**Issue by athewsey** [aws/sagemaker-experiments#75] opened 2020-06-11 08:55 UTC
**Describe the bug**

(Possibly related to #72 but I'm specifically working in SageMaker Studio)

Explicit `Tracker.log_metric()` calls raise a warning (see details below) and don't seem able to send metric data to SageMaker Experiments.

I've tried various combinations of:

- `Experiment.save()`, `Trial.save()`, `TrialComponent.save()` to flush metrics through to the API
- Wrapping tracker creation and metric logging in a `with Tracker.create(...) as tracker:` block in case being inside the context was necessary to log correctly

...but haven't found any working combination where I can explicitly call `log_metric()` and see the stored data through the SMExperiments API/UI.

**To Reproduce**

From a SageMaker Studio Python 3 (Data Science) kernel notebook:

```
experiment = Experiment.create(
    experiment_name=f"metrictestexp-{int(time.time())}",
    description="Trying to get metrics working",
)

tracker_nowith = Tracker.create(display_name="nowith-comp")

tracker_nowith.log_input(
    name="Raw input",
    media_type="text/csv",
    value="https://..."
)
tracker_nowith.log_parameters({
    "categorical_columns": [],
    "normalization_std": {},
    "aparam": 1,
})
tracker_nowith.log_output("train-csv", f"s3://...", "text/csv")

tracker_nowith.log_metric("my-cool-metric-name", 2501.4057)
```

The last log_metric line seems to raise the following **warning** (not Exception):
```
ERROR:root:'NoneType' object has no attribute 'write'
```

Input and output artifacts and parameters seem to be recorded and visible no problem, and a local `{PID}.json` file is generated but metrics are not visible through the Experiments APIs/UI.

`tracker_nowith.trial_component.metrics` returns `None`

**Expected behavior**

`log_metric()` to record the submitted named, scalar metric which should become visible through `TrialComponent.metrics` and the SageMaker Studio Experiments UI.

**Screenshots**

None

**Environment:**
Framework (e.g. TensorFlow) / Algorithm (e.g. KMeans): None
Framework Version: N/A
Python Version: 3.7.6
CPU or GPU: ml.t3.medium
Python SDK Version: smexperiments 0.1.14, sagemaker 1.60.0
Are you using a custom image: No - SMStudio Data Science kernel

**Additional context**

Use case is to record summary metrics derived from an in-notebook data preprocessing step: E.g. number of features after processing, summary statistics, etc.

**Comment by danabens** [comment] 2020-07-06 15:59
_Can't see log_metric() and see the stored data through the SMExperiments API/UI_

log_metric only logs to file currently. Eventually metrics will be logged server side and visible in API/UI, but no ETA.

_ERROR:root:'NoneType' object has no attribute 'write'_

This error was an indicator of the lazy-instantiation of the file writer and fixed in https://github.com/aws/sagemaker-experiments/pull/76

**Comment by shashankprasanna** [comment] 2020-07-10 22:15
@danabens 
What file does log_metric save the results to?
The documentation only says "Record a scalar metric value for this TrialComponent to file, not SageMaker."

That said, I've seen that log_metric does send the results to sagemaker, and can be queries with SageMaker Analytics. However, this seem to be inconsistent.

**Comment by athewsey** [comment] 2020-07-15 08:16
Agreed - as far as I can tell it only logs to a JSON file created in the same directory? I'm not sure I understand the use case for that functionality..?

+1 for getting SageMaker-side metric logging ASAP: There are custom output metrics (not parameters) of my Trial Components that I'd like to track as part of the SageMaker Experiment... E.g. per-field summary statistics after some pre-processing in a notebook or Processing Job.

**Comment by danabens** [comment] 2020-07-24 00:21
the file metrics writer writes to a file named <pid>.json . optionally, the environment variable SAGEMAKER_METRICS_DIRECTORY will determine the directory where the file is wriitten. code is [here](https://github.com/aws/sagemaker-experiments/blob/7ad1b979c67a2d6616c7a7ad8f5e1216e4fb0cd0/src/smexperiments/metrics.py#L84-L88).

> I've seen that log_metric does send the results to sagemaker
This are likely metrics generated by the job running in SageMaker rather than using log_metric via notebook.

**Comment by danabens** [comment] 2020-07-31 17:59
We recently fixed a metrics file buffering issue that may be related: https://github.com/aws/sagemaker-experiments/commit/bd48bdcae167df198fc7dbf66ff2d2a3508f2226

**Comment by danabens** [comment] 2020-08-07 20:27
Both issues (warning and not seeing metrics) are fixed and released. Let us know if you encounter any further issues.

**Closed by danabens** 2020-08-07 20:27 UTC

**Comment by Lewington-pitsos** [comment] 2022-01-29 01:35
I have exactly the same issue as @athewsey had originally. I have been trying for several hours to save experiments, trials and trial components in various orders such that `log_metrics` actually logs any metrics. I am calling `log_metrics` from a tracker created using `load` rather than `create`, inside a training job and no warnings are printed, but no matter what I do aws sagemaker studio and sagemaker experiments api seem unable to retrieve these metrics later (though parameters and artifacts are certainly logged).

@danabens can you provide a code snippet or the full code you ran before august 8 2020 that indicated to you that metrics are working as intended? This would possibly allow me to determine the source of my issue. 

Presently I am unable to find any similar code outlining the intended `log_metrics` workflow in either this repo or in `amazon-sagemaker-examples`.
